services:
  postgres:
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: always
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    networks:
      - db-network
  auth_db:
    image: postgres:16.0
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    restart: always
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    networks:
      - auth_network
  cli:
    image: postgres:16.0
    networks:
      - db-network
    command: psql -hpostgres -Uuser db
  auth_cli:
    image: postgres:16.0
    networks:
      - auth_network
    command: psql -hauth_db -Uuser auth_db

networks:
  db-network:
    driver: bridge
  auth_network:
    driver: bridge