# Dockerfile.db
FROM postgres:15

COPY .scripts/init-dbs.sh /docker-entrypoint-initdb.d/01-init-dbs.sh

# コンテナ初回起動時に実行される初期化スクリプトをコピー
COPY sql/app/ /docker-entrypoint-initdb.d/app-sql/
COPY sql/auth/ /docker-entrypoint-initdb.d/auth-sql/
