substitutions:
  _REGION: 'asia-northeast1'
  _CONTAINER: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}/recall-you-ml-prod:${SHORT_SHA}'
  _SERVICE_NAME: 'recall-you-ml-prod'

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'ubuntu'
    script: |
      touch .env

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - DOCKER_BUILDKIT=1
      - build
      - '-t'
      - '${_CONTAINER}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '${_CONTAINER}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE_NAME}'
      - '--image=${_CONTAINER}'
      - '--region=${_REGION}'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--port=8080'
      - '--allow-unauthenticated'
