name: CI (Web)

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/ci-web.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/ci-web.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  analyze:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    permissions:
      checks: write
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'
      - name: cache-node-modules
        uses: actions/cache@v3
        id: cache-node
        env:
          cache-name: cache-web
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-cache-web-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cache-web-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-
      - name: Install node modules
        if: ${{ steps.cache-node.outputs.cache-hit != 'true' }}
        run: pnpm i
      - name: Lint
        shell: bash
        run: npm run lint
      - name: Test
        shell: bash
        run: npm run test:unit
      - name: Build
        shell: bash
        run: npm run build

