name: Deploy to Firebase Functions on merge

on:
  push:
    branches:
      - main
    paths:
      - "firebase/functions/**"
      - ".github/workflows/deploy-functions.yaml"
  pull_request:

env:
  GCP_PROJECT_ID: "recall-you"
  GCP_SERVICE_ACCOUNT: "github-action-994212429@recall-you.iam.gserviceaccount.com"
  GCP_WORKLOAD_IDENTITY_PROVIDER: "projects/966744275445/locations/global/workloadIdentityPools/gh-pool/providers/gh-repo-provider"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write" # OIDC認証に必要
    defaults:
      run:
        working-directory: firebase

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: "firebase/functions/**/package-lock.json"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install backend dependencies
        run: npm --prefix "../backend" install

      - name: Install all Function dependencies
        run: |
          for dir in functions/*; do
            if [ -d "$dir" ] && [ -f "$dir/package.json" ]; then
              echo "--- Installing dependencies for $dir ---"
              npm --prefix "$dir" install
            fi
          done

      - name: Deploy to Firebase Functions
        run: firebase deploy --only functions --project ${{ env.GCP_PROJECT_ID }} --non-interactive
