name: Deploy Firebase Functions on merge

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'firebase/**'
      - '.github/workflows/deploy-functions.yaml'
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'firebase/**'
      - '.github/workflows/deploy-functions.yaml'

env:
  GCP_PROJECT_ID: 'recall-you'
  GCP_SERVICE_ACCOUNT: 'github-action-994212429@recall-you.iam.gserviceaccount.com'
  GCP_WORKLOAD_IDENTITY_PROVIDER: 'projects/966744275445/locations/global/workloadIdentityPools/gh-pool/providers/gh-repo-provider'

jobs:
  build_and_deploy_functions:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: 'backend/pnpm-lock.yaml'
      - name: Install backend dependencies
        run: pnpm i
        working-directory: backend
      - name: Cache npm dependencies for generate_profile
        uses: actions/cache@v4
        id: cache-npm-generate-profile
        with:
          path: firebase/functions/generate_profile/node_modules
          key: ${{ runner.os }}-node22-npm-generate-profile-${{ hashFiles('firebase/functions/generate_profile/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node22-npm-generate-profile-
      - name: Install generate_profile dependencies
        if: steps.cache-npm-generate-profile.outputs.cache-hit != 'true'
        run: npm install
        working-directory: firebase/functions/generate_profile
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase Functions
        run: firebase deploy --only functions --project ${{ env.GCP_PROJECT_ID }} --non-interactive
        working-directory: firebase
