services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.preview.web
    ports:
      - "3030:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - AUTH_SECRET=zJo1LhPpvhcpIzarFcz0AUqNxgitO5R2kqaulz5/B8I=
